name: login_server
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # widgets
  time_range: ^1.0.3

  # Architecture
  flutter_bloc: ^8.0.1
  auto_route: ^4.0.1
  get_it: ^7.2.0
  injectable: ^1.5.1
  provider: ^6.0.2

  # Data Processing
  lazy_load_scrollview: ^1.3.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  intl: ^0.17.0
  timeago: ^3.2.2
  timezone: ^0.8.0
  floor: ^1.2.0
  sqflite: ^2.0.2
  path: ^1.8.0
  device_info_plus: ^4.0.1

  # Network
  cached_network_image: 3.2.1
  internet_connection_checker:
  retrofit:
  dio:
  http:
  equatable: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  floor_generator:
  # injectable_generator: ^1.5.1
  # auto_route_generator:
  # retrofit_generator:
  flutter_lints: ^2.0.0
  mockito: ^5.3.0
  bloc_test: ^9.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/logo.png
    # - lib/features/presentations/src/img/logo/EkkremisLogo.png
    # - lib/features/presentations/src/img/logo/logo.png
    
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: lib/features/presentations/src/fonts/OpenSans.ttf
      
    - family: OpenSansItalic
      fonts:
        - asset: lib/features/presentations/src/fonts/OpenSansItalic.ttf
          weight: 100

    - family: ProximaNova
      fonts:
        - asset: lib/features/presentations/src/fonts/ProximaNovaFont.otf
          weight: 100
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
